@echo off
echo 🚀 Configurando TudoGestao Backend...
echo.
echo 1/5 Instalando dependencias...
call npm install
echo.
echo 2/5 Gerando Prisma Client...
call npx prisma generate
echo.
echo 3/5 Criando banco de dados...
call npx prisma migrate dev --name init
echo.
echo 4/5 Populando dados de demonstracao...
call npm run db:seed
echo.
echo 5/5 Iniciando servidor...
call npm run dev